In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [2]:
class FC:
    """
    ノード数n_nodes1からn_nodes2への全結合層
    Parameters
    ----------
    n_nodes1 : int
      前の層のノード数
    n_nodes2 : int
      後の層のノード数
    initializer : 初期化方法のインスタンス
    optimizer : 最適化手法のインスタンス
    """
    def __init__(self, n_nodes1, n_nodes2, initializer, optimizer):
        # 初期化
        # initializerのメソッドを使い、self.Wとself.Bを初期化する
        self.n_nodes1 = n_nodes1
        self.n_nodes2 = n_nodes2
        self.optimizer = optimizer
        #self.W = initializer.W(self.n_nodes1, self.n_nodes2)
        #self.B = initializer.B(self.n_nodes2)
        self.W = np.array([3,5,7]) 
        self.B = np.array([1])
        self.P = 0
        self.Str = 1
        self.s = len(self.W)
        self.a = np.array([])
        self.dW = np.array([])
        self.dX = np.array([])

    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes_bf)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes_af)
            出力
        """
        #self.X = X
        self.X = X
        self.Xsize = len(self.X)
        self._output_size()
        
        self.a = np.append(self.a, np.array([(self.X[i:i+self.s] @ self.W.T + self.B) for i in range(self.Nout)]))
        return self.a
    
    def _output_size(self):
        self.Nout = int((len(self.X) + 2*self.P - self.s) / self.Str + 1)       
    
    def backward(self, dA):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """
        self.dB = np.sum(dA, axis=0)
        self.dW = np.append(self.dW, np.array([(dA @ self.X[i:i+self.Nout].T) for i in range(self.s)]))

        for j in range(len(self.X)):
            if j-self.Nout < 0:
                #display(j)
                #display(np.flip(self.W[ : self.s-(self.Nout-j) ]))
                #display(dA[:j+1])
                self.dX = np.append(self.dX, (dA[:j+1] @ np.flip(self.W[ : self.s-(self.Nout-j) ]).T))
                
            elif j > len(self.X) - self.Nout:
                #display(j)
                #display(np.flip(dA    [-(j-(self.Xsize - self.Nout)):]))
                #display(np.flip(self.W[-(j-(self.Xsize - self.Nout)):]))
                self.dX = np.append(self.dX, (np.flip(dA    [-(j-(self.Xsize - self.Nout)):])) @ 
                                              np.flip(self.W[-(j-(self.Xsize - self.Nout)):]).T)
            else:
                #display(j)
                #display(np.flip(self.W[ j-self.Nout+1 : j+1 ]))
                self.dX = np.append(self.dX, (dA @ np.flip(self.W[ j-self.Nout+1 : j+1 ]).T))

        # 更新
        #self.W = self.optimizer.update(dW, self.W)
        #self.B = self.optimizer.update(dB, self.B)

        return self.dX


In [3]:
x = np.array([1,2,3,4])
w = np.array([3, 5, 7])
b = np.array([1])
test = FC(1,2,3,4)

In [4]:
test.forward(x)

array([35., 50.])

In [5]:
delta_a = np.array([10, 20])
test.backward(delta_a)

array([ 30., 110., 170., 140.])

In [6]:
display(test.dB)
display(test.dW)

30

array([ 50.,  80., 110.])

In [7]:
class Conv1d:
    """
    ノード数n_nodes1からn_nodes2への全結合層
    Parameters
    ----------
    n_nodes1 : int
      前の層のノード数
    n_nodes2 : int
      後の層のノード数
    initializer : 初期化方法のインスタンス
    optimizer : 最適化手法のインスタンス
    """
    def __init__(self, n_nodes1, n_nodes2, initializer, optimizer):
        # 初期化
        # initializerのメソッドを使い、self.Wとself.Bを初期化する
        self.n_nodes1 = n_nodes1
        self.n_nodes2 = n_nodes2
        self.optimizer = optimizer
        #self.W = initializer.W(self.n_nodes1, self.n_nodes2)
        #self.B = initializer.B(self.n_nodes2)
        self.W = np.array([3,5,7]) 
        self.B = np.array([1])
        self.P = 0
        self.Str = 1
        self.s = len(self.W)
        self.a = np.array([])
        self.dW = np.array([])
        self.dX = np.array([])

    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes_bf)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes_af)
            出力
        """
        #self.X = X
        self.X = X
        self.Xsize = len(self.X)
        self._output_size()
        
        self.a = np.append(self.a, np.array([(self.X[i:i+self.s] @ self.W.T + self.B) for i in range(self.Nout)]))
        return self.a
    
    def _output_size(self):
        self.Nout = int((len(self.X) + 2*self.P - self.s) / self.Str + 1)       
    
    def backward(self, dA):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """
        self.dB = np.sum(dA, axis=0)
        self.dW = np.append(self.dW, np.array([(dA @ self.X[i:i+self.Nout].T) for i in range(self.s)]))

        for j in range(len(self.X)):
            if j-self.Nout < 0:
                #display(j)
                #display(np.flip(self.W[ : self.s-(self.Nout-j) ]))
                #display(dA[:j+1])
                self.dX = np.append(self.dX, (dA[:j+1] @ np.flip(self.W[ : self.s-(self.Nout-j) ]).T))
                
            elif j > len(self.X) - self.Nout:
                #display(j)
                #display(np.flip(dA    [-(j-(self.Xsize - self.Nout)):]))
                #display(np.flip(self.W[-(j-(self.Xsize - self.Nout)):]))
                self.dX = np.append(self.dX, (np.flip(dA    [-(j-(self.Xsize - self.Nout)):])) @ 
                                              np.flip(self.W[-(j-(self.Xsize - self.Nout)):]).T)
            else:
                #display(j)
                #display(np.flip(self.W[ j-self.Nout+1 : j+1 ]))
                self.dX = np.append(self.dX, (dA @ np.flip(self.W[ j-self.Nout+1 : j+1 ]).T))

        # 更新
        #self.W = self.optimizer.update(dW, self.W)
        #self.B = self.optimizer.update(dB, self.B)

        return self.dX


### 【問題4】チャンネル数を限定しない1次元畳み込み層クラスの作成 
チャンネル数を1に限定しない1次元畳み込み層のクラスConv1dを作成してください。

In [8]:
import itertools
import pprint

In [123]:
class Conv1d:
    """
    ノード数n_nodes1からn_nodes2への全結合層
    Parameters
    ----------
    n_nodes1 : int
      前の層のノード数
    n_nodes2 : int
      後の層のノード数
    initializer : 初期化方法のインスタンス
    optimizer : 最適化手法のインスタンス
    """
    def __init__(self):
        self.P = 0
        self.Str = 1
        self.a = np.array([])
        self.dW = np.array([])
        self.dX = np.array([])
        #self.s=None
        
    def forward(self, X, W ,B):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes_bf)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes_af)
            出力
        """
        self.X = X
        self.Xsize = self.X.shape[1]
        self.W = W 
        self.B = B
        self.s = self.W.shape[2]
        
        self._output_size()
        self.a = np.append(self.a, np.array([np.sum(self.X[:, i:i+self.s] * self.W[i0,:,:]) + self.B[i0] 
                                             for i0,i in itertools.product(range(self.W.shape[0]), range(self.Nout))]))
        self.a = self.a.reshape(self.W.shape[0], self.Nout)
        return self.a
    
    def _output_size(self):
        self.Nout = int((self.Xsize + 2*self.P - self.s) / self.Str + 1)       
    
    def backward(self, dA):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """
        self.dB = np.sum(dA, axis=1)   
        
        for i0 in range(self.W.shape[0]):
            dX_ary = np.zeros((self.W.shape[1], self.W.shape[2]))
            for i in range(self.Nout):
                dX_ary += dA[i0,i] * self.X[:, i:i+self.s]
            self.dW = np.append(self.dW, dX_ary)
        self.dW = self.dW.reshape(3,2,3)
        """検討中
        self.Xp=np.array([self.X]*self.W.shape[0])
        self.
        self.dW= np.zeros((self.W.shape))
        self.dW = [self.dW + (dA * self.Xp[:,:,i:i+self.s]) for i in range(self.Nout)]
        """
        #self.dW = np.append(self.dW, [dX_ary + (np.ones((self.W[1].shape, self.W[2].shape))*dA[i0,i]) * self.X[:, i:i+self.Nout] 
        #                              for i in range(self.Nout)] for i0 in range(self.W.shape[0]))
        
        #for j in range(len(self.X)):
        #    if j-self.Nout < 0:
        #        self.dX = np.append(self.dX, (dA[:j+1] @ np.flip(self.W[ : self.s-(self.Nout-j) ]).T))
        #        
        #    elif j > len(self.X) - self.Nout:
        #        self.dX = np.append(self.dX, (np.flip(dA    [-(j-(self.Xsize - self.Nout)):])) @ 
        #                                      np.flip(self.W[-(j-(self.Xsize - self.Nout)):]).T)
        #    else:
        #        self.dX = np.append(self.dX, (dA @ np.flip(self.W[ j-self.Nout+1 : j+1 ]).T))

        return self.dW
    
    #def _naiseki_plus(self,dA):
    #    dX_ary = np.zeros((self.W[1].shape, self.W[2].shape))
    #    dX_ary = [dX_ary + (np.ones((self.W[1].shape, self.W[2].shape))*dA[i0,i]) * self.X[:, i:i+self.Nout] for i in range(self.Nout)]
    #    return dX_ary

In [124]:
x = np.array([[1, 2, 3, 4], [2, 3, 4, 5]]) # shape(2, 4)で、（入力チャンネル数、特徴量数）である。
w = np.ones((3, 2, 3)) # 例の簡略化のため全て1とする。(出力チャンネル数、入力チャンネル数、フィルタサイズ)である。
b = np.array([1, 2, 3]) # （出力チャンネル数）

In [125]:
test2dim = Conv1d()
test2dim.forward(x,w,b)

array([[16., 22.],
       [17., 23.],
       [18., 24.]])

In [126]:
x = np.array([[2, 3, 4, 5], [1, 2, 3, 4]]) # shape(2, 4)で、（入力チャンネル数、特徴量数）である。
#w = np.ones((3, 2, 3)) # 例の簡略化のため全て1とする。(出力チャンネル数、入力チャンネル数、フィルタサイズ)である。
w = np.array([[[1,1,1],
            [1,1,1]],
            [[1,1,1],
            [2,1,1]],
            [[2,1,1],
            [1,1,2]]])
b = np.array([3, 2, 1]) # （出力チャンネル数）

In [127]:
test2dim = Conv1d()
test2dim.forward(x,w,b)

array([[18., 24.],
       [18., 25.],
       [21., 29.]])

### バックプロパゲーションの確認

In [128]:
dA = np.array([[52,56],
            [32,35],
            [9,11]])
#dA = np.array([9,11])

In [129]:
dA3=np.array([dA]*3)
dA3

array([[[52, 56],
        [32, 35],
        [ 9, 11]],

       [[52, 56],
        [32, 35],
        [ 9, 11]],

       [[52, 56],
        [32, 35],
        [ 9, 11]]])

In [130]:
dA3=dA3.transpose(1,2,0)
dA3

array([[[52, 52, 52],
        [56, 56, 56]],

       [[32, 32, 32],
        [35, 35, 35]],

       [[ 9,  9,  9],
        [11, 11, 11]]])

In [131]:
test2dim.backward(dA)

array([[[272., 380., 488.],
        [164., 272., 380.]],

       [[169., 236., 303.],
        [102., 169., 236.]],

       [[ 51.,  71.,  91.],
        [ 31.,  51.,  71.]]])

In [99]:
np.array([x]*3)

array([[[2, 3, 4, 5],
        [1, 2, 3, 4]],

       [[2, 3, 4, 5],
        [1, 2, 3, 4]],

       [[2, 3, 4, 5],
        [1, 2, 3, 4]]])