### Week2 授業前課題3 行列積のスクラッチ

In [ ]:
a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6], 
                      [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                      [0, 2, -8],
                      [2, 9, -1]])

### 【問題1】行列積を手計算する¶
AとBの行列積を手計算で解いてください。 計算過程もマークダウンテキストを用いて説明してください。

A×B = [[-1×0 + 2×0 + 3×2 , -1×2 + 2×2 + 3×9 , -1×1 + 2×(-8) + 3×(-1)], [4×0 + (-5)×0 + 6×2 , 4×2 + (-5)×2 + 6×9 , 4×1 + (-5)× (-8) + 6×(-1)], [7×0 + 8×0 + (-9)×2 , 7×2 + 8×2 + (-9)×9 , 7×1 + 8×(-8) + (-9)×(-1)]]

= [[6, 29, -20], [12, 52, 38], [-18, -51, -48]]

### 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

■3種類の違い

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。

In [72]:
#問題２
import numpy as np
def func_naiseki_a(def_array1, def_array2):
    return def_array1 @ def_array2
def func_naiseki_matmul(def_array1, def_array2):
    return np.matmul(def_array1,def_array2)
def func_naiseki_dot(def_array1, def_array2):
    return np.dot(def_array1,def_array2)

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

result_naiseki_a = func_naiseki_a(a_ndarray, b_ndarray) 
result_naiseki_matmul = func_naiseki_matmul(a_ndarray, b_ndarray) 
result_naiseki_dot = func_naiseki_dot(a_ndarray, b_ndarray) 

print(result_naiseki_a)
print(result_naiseki_matmul)
print(result_naiseki_dot)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 【問題3】ある要素の計算を実装¶
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

・行列Aの(0,0)の要素a0,0と行列Bの(0,0)の要素b0,0を掛け合わせる
・行列Aの(0,1)の要素a0,1と行列Bの(1,0)の要素a1,0を掛け合わせる
・行列Aの(0,2)の要素a0,2と行列Bの(2,0)の要素a2,0を掛け合わせる
・それらの値を全て足し合わせる
この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [73]:
#問題３
def func_naiseki_manual(def_array1, def_array2):
        def_ary_0_0 = def_array1[0,0]*def_array2[0,0] + def_array1[0,1]*def_array2[1,0] + def_array1[0,2]*def_array2[2,0]
        def_ary_1_0 = def_array1[1,0]*def_array2[0,0] + def_array1[1,1]*def_array2[1,0] + def_array1[1,2]*def_array2[2,0]
        def_ary_2_0 = def_array1[2,0]*def_array2[0,0] + def_array1[2,1]*def_array2[1,0] + def_array1[2,2]*def_array2[2,0]
        
        def_ary_0_1 = def_array1[0,0]*def_array2[0,1] + def_array1[0,1]*def_array2[1,1] + def_array1[0,2]*def_array2[2,1]
        def_ary_1_1 = def_array1[1,0]*def_array2[0,1] + def_array1[1,1]*def_array2[1,1] + def_array1[1,2]*def_array2[2,1]
        def_ary_2_1 = def_array1[2,0]*def_array2[0,1] + def_array1[2,1]*def_array2[1,1] + def_array1[2,2]*def_array2[2,1]
        
        def_ary_0_2 = def_array1[0,0]*def_array2[0,2] + def_array1[0,1]*def_array2[1,2] + def_array1[0,2]*def_array2[2,2]
        def_ary_1_2 = def_array1[1,0]*def_array2[0,2] + def_array1[1,1]*def_array2[1,2] + def_array1[1,2]*def_array2[2,2]
        def_ary_2_2 = def_array1[2,0]*def_array2[0,2] + def_array1[2,1]*def_array2[1,2] + def_array1[2,2]*def_array2[2,2]

        def_result_array = np.array([[def_ary_0_0,def_ary_0_1,def_ary_0_2],
                                    [def_ary_1_0,def_ary_1_1,def_ary_1_2],
                                    [def_ary_2_0,def_ary_2_1,def_ary_2_2]])        
        return def_result_array
result_array = func_naiseki_manual(a_ndarray, b_ndarray)
result_array

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### 【問題4】行列積を行う関数の作成¶
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。 行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。 計算結果である 3×3 の行列Cの各要素 cij は数式で表すと次のようになります。 for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス iやjを1増やすと、次の行や列に移ることができます。

In [74]:
#問題４
def func_naiseki_manual2(def_array1, def_array2):
        def_result_array = np.zeros(def_array1.shape[0]*def_array2.shape[1]).reshape(def_array1.shape[0],def_array2.shape[1])
        
        row=0
        col=0
        for row in range(def_array1.shape[0]):
            for col in range(def_array2.shape[1]):
                for kou in range(def_array1.shape[1]):
                    def_result_array[row,col] += def_array1[row,kou]*def_array2[kou,col]
                col += 1
            row +=1
        return def_result_array
result_array = func_naiseki_manual2(a_ndarray, b_ndarray)
result_array

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

### 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。 if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [75]:
#問題５
def func_naiseki_manual3(def_array1, def_array2):
        def_result_array = np.zeros(def_array1.shape[0]*def_array2.shape[1]).reshape(def_array1.shape[0],def_array2.shape[1])
        if def_array1.shape[1] != def_array2.shape[0]:
            return print("Can't calcurate. Because array1's columns don't equal to array2's raws") 
        else:
            row=0
            col=0
            for row in range(def_array1.shape[0]):
                for col in range(def_array2.shape[1]):
                    for kou in range(def_array1.shape[1]):
                        def_result_array[row,col] += def_array1[row,kou]*def_array2[kou,col]
                    col += 1
                row +=1
            return def_result_array

d_ndarray_ = np.array([[-1, 2, 3], 
                       [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], 
                      [6, -5, 4]])
result_array = func_naiseki_manual3(d_ndarray_, e_ndarray)
result_array

Can't calcurate. Because array1's columns don't equal to array2's raws


### 【問題6】転置¶
片方の行列を転置することで、行列積が計算できるようになります。 np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [76]:
#問題６
result_array = func_naiseki_manual3(d_ndarray_.T, e_ndarray)
result_array

array([[ 33., -28.,   9.],
       [-48.,  41.,  -6.],
       [  9.,  -6.,  45.]])